services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fin-ng-backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB} }?sslmode=disable
      - JWT_SECRET=${{ secrets.JWT_SECRET }}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:15
    container_name: fin-ng-db
    restart: always
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${{ secrets.POSTGRES_USER}} -d ${{ secrets.POSTGRES_DB }}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
