services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fin-ng-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    container_name: fin-ng-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
