name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set environment variables
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > backend/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> backend/.env
          echo "POSTGRES_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}?sslmode=disable" >> backend/.env
          echo "POSTGRES_TEST_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db_test:5432/finance_tracker_test?sslmode=disable" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env

      - name: Build and start services with Docker Compose
        run: |
          cd backend
          docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          sleep 30  
          docker exec fin-ng-db pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}
          docker exec fin-ng-db-test pg_isready -U ${{ secrets.POSTGRES_USER }} -d finance_tracker_test

      - name: Debug container logs
        run: |
          cd backend
          docker-compose logs app
          docker-compose logs db
          docker-compose logs db_test

      - name: Run tests (optional)
        run: |
          cd backend
          docker run --rm -v $(pwd):/app -w /app --network backend_backend \
            -e POSTGRES_TEST_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db_test:5432/finance_tracker_test?sslmode=disable \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            golang:1.24.4 go test ./api -v \
            golang:1.24.4 go test ./db -v
        continue-on-error: true

      - name: Check API health
        run: |
          curl --fail http://localhost:8080/swagger/index.html || exit 1

      - name: Stop services
        run: |
          cd backend
          docker-compose down
